# Generated by Django 4.1.7 on 2023-08-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='qr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.qr'),
        ),
    ]
