# Generated by Django 4.1.7 on 2023-08-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_scan_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='counter',
        ),
        migrations.AddField(
            model_name='qr',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
