# Generated by Django 4.1.7 on 2023-08-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_scan_counter_qr_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
