# Generated by Django 4.1.7 on 2023-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_qr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
